### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sanchezzzov** [drud/typo3-v9-test#1]
> typo3-v9-test/vendor/symfony/console/Tests/Command/CommandTest.php

This file has private static method createClosure, where $this is not accessible in static context
Screenshot: http://joxi.ru/V2V6wzdcxJZye2

**Comment by rfay** [comment]
@sanchezzzov this repo is only for automated testing of github.com/drud/ddev, if you want help with some TYPO3 issue, there are places for that. Probably the TYPO3 issue queue. Happy to help direct you further, but this is absolutely not the place. For help getting to the right place, try the TYPO3 slack maybe? https://my.typo3.org/index.php?id=35
